apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunnybikes
  namespace: sunnybikes
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
    matchLabels:
      app: sunnybikes
  template:
    metadata:
      labels:
        app: sunnybikes
    spec:
      containers:
        - name: sunnybikes
          image: pugillum/sunnybikes:stable
          imagePullPolicy: Always
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            httpGet:
              port: 5000
              path: /healthz
