apiVersion: v1
kind: Pod
metadata:
  name: sunnybikes
  namespace: sunnybikes
spec:
  containers:
    - name: sunnybikes-api
      image: pugillum/sunnybikes:stable
      imagePullPolicy: IfNotPresent
