apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: sunnybikes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sunnybikes
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: init
            - mountPath: /var/lib/postgresql/data
              name: data
              subPath: data
          ports:
            - containerPort: 5432
      volumes:
        - name: init
          configMap:
            name: postgres-init
        - name: data
          persistentVolumeClaim:
            claimName: pvc-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sunnybikes
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
